Models/ErrorViewModel.cs
namespace App.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/PlanetModel.cs
namespace App.Models;

public class PlanetModel
{
    public int Id {get; set;}   
    public string Name {get; set;}

    public string VnName {get; set;}

    public string Content {get; set;}
}

Models/ProductModel.cs
namespace App.Models
{
    public class ProductModel
    {
        public int id {get; set;}
        public string ? name {get; set;}
        public double price {get; set;}

    
    }

}

Controllers/FirstController.cs
using Microsoft.AspNetCore.Mvc;
using System.IO;
using App.Sevice;
using App.Models;

namespace App.Controllers
{

    public class FirstController: Controller
    {
        
        private readonly ILogger<FirstController> _logger;
        private readonly ProductSevice _productSevice;
        public FirstController(ILogger<FirstController> logger, ProductSevice procductSevice)
        {
            _logger = logger;
            _productSevice=procductSevice;
        } 
        //this.HttpContext;
        //this.HttpRequest;
        //this.HttpResponse;
        //this.RouteData;
        //ngoài ra là các thuộc tính như sử dụng pagemodel
        // this.user
        // this.url

        
        public string Index()
        {
            //LogLevel có 6 cấp độ để theo dõi ứng dụng
            //ví dụ như:
            // _logger.LogWarning("thông báo");
            // _logger.LogError("thông báo");
            // _logger.LogInformation("thông báo");
            // _logger.LogDebug("thông báo");
            // _logger.LogTrace("thông báo");
            // _logger.LogCritical("thông báo");
            //ngoài ra có thể đăng ký các dịch vụ thay thế ví dụ như serilog,...
            //_logger.LogInformation("action index");
            return "tôi là index của first";
        }
        //các action có thể trả về bất cứ kiểu dữ liệu nào, nó sẽ được convert thành
        //chuỗi để trả về cho client
        public void Nothing(){
            _logger.LogInformation("notthing action");
            Response.Headers.Add("hi", "xin chao cac ban");
        }
        public object Anything(){
            return DateTime.Now;//ở đây đã được convert thành chuỗi chuyển về 
            //giao diện cho client
            //tuy nhiên các đối tượng trả về từ action thường là các đối tượng
            //được triển khai từ IactionResult
        }
        public IActionResult Readme()
        {
            string rs=@"
            xin chào các bạn
            chúng ta đang học aspnet mvc


            trung nguyen
            ";
            return this.Content(rs, "text/html");
            //sẽ được thư viện chuyển nội dung rs thành response trả về
        }
        // public IActionResult logo()
        // {
        public IActionResult logo(){
            string path=@"E:\C SHARP\AppMvc.Net\Files\logoMu.jpg";
            var bytes= System.IO.File.ReadAllBytes(path);
            return File(bytes, "image/jpg");
        }

        public IActionResult product()
        {
            var product= new {
                name="samsung",
                Model="14 pro max",
                price=1500
            };
            return Json(product);
        }


        public IActionResult goole()
        {
            return Redirect("https://www.google.gg/");
        }
        // }
        
    //     Kiểu trả về                 | Phương thức
    // ------------------------------------------------
    // ContentResult               | Content()
    // EmptyResult                 | new EmptyResult() tương đương trả về void
    // FileResult                  | File()
    // ForbidResult                | Forbid()
    // JsonResult                  | Json()
    // LocalRedirectResult         | LocalRedirect()
    // RedirectResult              | Redirect()
    // RedirectToActionResult      | RedirectToAction()
    // RedirectToPageResult        | RedirectToRoute()
    // RedirectToRouteResult       | RedirectToPage()

    // PartialViewResult           | PartialView() đã có trong phần razor page
    // ViewComponentResult         | ViewComponent() đã có trong phần razor page
    // StatusCodeResult            | StatusCode()
    // ViewResult                  | View() => phương thức quan trọng nhất

        public IActionResult helloview(string user)
        {
            //view sử dụng razor engineer để đọc file .cshtml(temple) 
            //trả về nội dung cho client
            //mặc định sẽ vào phần "View/controller/action" ~ đường dẫn trong view
            // return View();
            // return View(@"Views\first\view1.cshtml");
            //~ trong phương thức view có thể truyền 2 tham số(tham số 1 là đường 
            //  dẫn tuyệt đối, tham số thứ 2 là model)
            //các cách truyền dữ liệu sang view:
            //_model, viewdata,viewbag , temdata. 
            // user ="khach";
            return View("xinchao2");//Myviews/First/xinchao2 ~ Myviews/controller/action
        }
        public IActionResult viewproduct(int ? id)//id được bingding đến thông qua url
        {
            //ProductModel _product;
            var product = _productSevice.Where(p=>p.id==id).FirstOrDefault();
            if(product == null){
                TempData["error"]="sản phẩm không tồn tại!";
                return Redirect( "/home/index");
            }
            // return View(product);
            // this.ViewData["product"]=product;
            // this.ViewData["Title"]=product.name;

            this.ViewBag.product=product;
            return View();
        }

    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using App.Models;

namespace App.Controllers;

public class HomeController : Controller //tên controller là home
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    
    public IActionResult Index() //có 1 phương thức là index
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/PlanetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using App.Sevice;

namespace App.Controllers
{
    [Route("he-mat-troi/[action]")]
    public class PlanetController : Controller
    {
        private readonly PlanetSevice planets;
        private readonly ILogger<PlanetController> logger;

        public PlanetController(PlanetSevice planets, ILogger<PlanetController> logger)
        {
            this.planets = planets;
            this.logger = logger;
        }

        [Route("/danh-sach-cac-hanh-tinh")]
        public IActionResult Index()
        {
            return View();
        }

        [BindProperty(SupportsGet =true, Name ="action")]
        public string Name{get; set;}
        public IActionResult Mercury()
        {
            var planet=planets.Where(p=>p.Name==Name).FirstOrDefault();
            return View("Detail", planet);
        }
        public IActionResult Venus()
        {
            var planet=planets.Where(p=>p.Name==Name).FirstOrDefault();
            return View("Detail", planet);
        }
        public IActionResult Jupiter()
        {
            var planet=planets.Where(p=>p.Name==Name).FirstOrDefault();
            return View("Detail", planet);
        }
        public IActionResult Earth()
        {
            var planet=planets.Where(p=>p.Name==Name).FirstOrDefault();
            return View("Detail", planet);
        }
        public IActionResult Mars()
        {
            var planet=planets.Where(p=>p.Name==Name).FirstOrDefault();
            return View("Detail", planet);
        }
        public IActionResult Uranus()
        {
            var planet=planets.Where(p=>p.Name==Name).FirstOrDefault();
            return View("Detail", planet);
        }
        public IActionResult Saturn()
        {
            var planet=planets.Where(p=>p.Name==Name).FirstOrDefault();
            return View("Detail", planet);
        }
        public IActionResult Neptune()
        {
            var planet=planets.Where(p=>p.Name==Name).FirstOrDefault();
            return View("Detail", planet);
        }

        [Route("hanhtinh/{id:int}")]
        public IActionResult Infor(int id)
        {
            var planet=planets.Where(p=>p.Id==id).FirstOrDefault();
            return View("Detail", planet);
        }
    }
}

Pages/Razor.cshtml
@page "/aboutrazor.cshtml"
@{
    Layout ="_Layout";
}
<h1>Gioi thieu ve razor page</h1>
<p>
    razor là 1 template engineer trong .net, là template mặc định của aspnet mvc, 
    có chức năng render (dựng html từ các view) có thể viết cả code c # và html
</p>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<partial name="errorproduct"></partial>
<div class="text-center">
    <h1 class="display-4">xin chào</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Home/errorproduct.cshtml
@if(TempData["error"] !=null)
{
    <div class="alert alert-warning" role="alert">
  @TempData["error"]
</div>
}

Views/Planet/Detail.cshtml
@model App.Models.PlanetModel;

<h1>@Model.Name</h1>
<div class="card w-50">
    <h4>@Model.VnName</h2>
    @if(@Model.Name=="Mars")
    {
        <img src="~/planet/@(Model.Name).png" alt="">
    }
    <img src="~/planet/@(Model.Name).jpg" alt="">
    <div class="card-body">
        <div class="card-text">
            @Model.Content
        </div>
        <a class="card-link" asp-action="Index">Danh sách các hành tinh</a>
    </div>
</div>

Views/Planet/Index.cshtml
@inject App.Sevice.PlanetSevice planetSevice

<div class="list-group">
    @foreach (var planet in planetSevice)
{
    <a asp-controller="Planet" asp-action="@planet.Name" class="list-group-item list-group-item-action">
        @planet.Name-@planet.VnName
    </a>
}
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/App.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">App</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Planet" asp-action="Index">Planet</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - App - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>